// This file is automatically generated by the Tailwind CSS CLI.

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],  theme: {
    extend: {
      colors: {
        primary: "hsl(199, 100%, 33%)",
        secondary: "hsl(187, 100%, 43%)",
        gradient: "linear-gradient(to right, hsl(187, 85%, 43%), hsl(199, 100%, 33%))",
        whiteText: "hsl(0, 0%, 10%)",
        textColor: "hsl(240, 4%, 36%)",
        blackColor: "hsl(201, 33%, 16%)",
        grayText: "rgb(190, 190, 190)",
        whiteColorDeam: "hsl(190, 0%, 30%)",
        inputColor: "rgb(239, 239, 239)",
        bodyColor: "rgb(240 , 240, 249)",
        cardBGColor: "rgb(225 , 225 , 235)",
        overLay : "rgba(47, 106, 127)",
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          sm: '2rem',
          lg: '4rem',
          xl: '5rem',
          '2xl': '6rem',
        },
      },
    },
  },
  plugins: [],
}

